/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Medina
 */
public class ViewMaster extends javax.swing.JFrame {

    /**
     * Creates new form ViewAsuransi
     */
    public ViewMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        dekstopAs = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuAdmin = new javax.swing.JMenu();
        menuMaster = new javax.swing.JMenu();
        menuNasabah = new javax.swing.JMenuItem();
        menuPolis = new javax.swing.JMenuItem();
        menuAsuransi = new javax.swing.JMenuItem();
        menuPembayaran = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dekstopAs.setBackground(java.awt.Color.lightGray);
        dekstopAs.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dekstopAs.setForeground(new java.awt.Color(102, 102, 102));
        dekstopAs.setToolTipText("Home Asuransi");
        dekstopAs.setFocusTraversalPolicyProvider(true);
        dekstopAs.setLayout(new javax.swing.OverlayLayout(dekstopAs));

        menuHome.setText("Home");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHome);

        menuAdmin.setText("Admin");
        menuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdminMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAdmin);

        menuMaster.setText("Master");

        menuNasabah.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNasabah.setText("Nasabah");
        menuNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNasabahActionPerformed(evt);
            }
        });
        menuMaster.add(menuNasabah);

        menuPolis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPolis.setText("Polis");
        menuPolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPolisActionPerformed(evt);
            }
        });
        menuMaster.add(menuPolis);

        menuAsuransi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAsuransi.setText("Asuransi");
        menuAsuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsuransiActionPerformed(evt);
            }
        });
        menuMaster.add(menuAsuransi);

        jMenuBar1.add(menuMaster);

        menuPembayaran.setText("Pembayaran");
        menuPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPembayaranMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPembayaran);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dekstopAs, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dekstopAs, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dekstopAs.getAccessibleContext().setAccessibleName("Home Asuransi");
        dekstopAs.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNasabahActionPerformed
        ViewNasabah frame = new ViewNasabah();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuNasabahActionPerformed

    private void menuPolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPolisActionPerformed
        ViewPolis frame = new ViewPolis();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuPolisActionPerformed

    private void menuAsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsuransiActionPerformed
        ViewAsuransi frame = new ViewAsuransi();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuAsuransiActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        ViewHome frame = new ViewHome();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdminMouseClicked
        ViewAdmin frame = new ViewAdmin();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuAdminMouseClicked

    private void menuPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPembayaranMouseClicked
        ViewPembayaran frame = new ViewPembayaran();
        frame.show();
        dekstopAs.add(frame);
    }//GEN-LAST:event_menuPembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstopAs;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuAsuransi;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuNasabah;
    private javax.swing.JMenu menuPembayaran;
    private javax.swing.JMenuItem menuPolis;
    // End of variables declaration//GEN-END:variables
}
